package org.godot.internal.dispatch;

/**
 * Compile-time metadata for a @GodotMethod method, generated by APT into
 * DispatchIndex.
 */
public record MethodMeta(String javaName, String godotName, String returnType, String[] paramTypes,
		String[] paramNames) {
}
