package org.godot.internal.dispatch;

/**
 * Compile-time metadata for an @Export field, generated by APT into
 * DispatchIndex.
 */
public record PropertyMeta(String javaName, String godotName, String typeName, int hintId, String hintString, int usage,
		String getter, String setter, boolean readOnly, String group, String groupHint, String subgroup,
		String subgroupHint) {

	public PropertyMeta(String javaName, String godotName, String typeName, int hintId, String hintString) {
		this(javaName, godotName, typeName, hintId, hintString, 1 | 2 | 4 | 8, "", "", false, "", "", "", "");
	}

	public PropertyMeta(String javaName, String godotName, String typeName, int hintId, String hintString, int usage,
			String group, String groupHint, String subgroup, String subgroupHint) {
		this(javaName, godotName, typeName, hintId, hintString, usage, "", "", false, group, groupHint, subgroup,
				subgroupHint);
	}
}
