package org.godot.internal.dispatch;

/**
 * Compile-time metadata for an @Export field, generated by APT into
 * DispatchIndex.
 */
public record PropertyMeta(String javaName, String godotName, String typeName, int hintId, String hintString) {
}
