package org.godot.internal.dispatch;

/**
 * Compile-time metadata for a @Signal method, generated by APT into
 * DispatchIndex.
 */
public record SignalMeta(String name, String[] paramTypes, String[] paramNames) {
}
