package org.godot.bridge;

import org.godot.Godot;
import org.godot.annotation.Export;
import org.godot.annotation.GodotClass;
import org.godot.annotation.PropertyHint;
import org.godot.core.GodotString;
import org.godot.core.Variant;
import org.godot.core.VariantUtils;
import org.godot.internal.api.VariantType;
import org.godot.internal.ref.JavaObjectMap;
import org.godot.core.GodotStringName;
import org.godot.internal.api.ApiIndex;
import org.godot.internal.api.StructOffsets;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.Method;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import static java.lang.foreign.ValueLayout.*;
import java.lang.foreign.ValueLayout;

/**
 * Handles GDExtensionClassCreationInfo4 struct creation and the create/free
 * instance upcall stubs required by Godot's ClassDB class registration API.
 *
 * <p>
 * When Godot calls classdb_register_extension_class5(), it receives a pointer
 * to a GDExtensionClassCreationInfo4 struct containing function pointers for
 * lifecycle callbacks. The two mandatory callbacks are:
 *
 * <ul>
 * <li>{@code create_instance_func}: called when Godot needs to instantiate the
 * class
 * <li>{@code free_instance_func}: called when Godot destroys an instance
 * </ul>
 *
 * <p>
 * This class creates Panama upcall stubs for those callbacks and allocates the
 * struct in native memory with all fields populated.
 *
 * <p>
 * GDExtensionClassCreationInfo4 layout (22 fields, 176 bytes on 64-bit):
 * <ol start="0">
 * <li>GDExtensionBool is_virtual
 * <li>GDExtensionBool is_abstract
 * <li>GDExtensionBool is_exposed
 * <li>GDExtensionBool is_runtime
 * <li>GDExtensionConstStringPtr icon_path
 * <li>GDExtensionClassSet set_func
 * <li>GDExtensionClassGet get_func
 * <li>GDExtensionClassGetPropertyList get_property_list_func
 * <li>GDExtensionClassFreePropertyList2 free_property_list_func
 * <li>GDExtensionClassPropertyCanRevert property_can_revert_func
 * <li>GDExtensionClassPropertyGetRevert property_get_revert_func
 * <li>GDExtensionClassValidateProperty validate_property_func
 * <li>GDExtensionClassNotification2 notification_func
 * <li>GDExtensionClassToString to_string_func
 * <li>GDExtensionClassReference reference_func
 * <li>GDExtensionClassUnreference unreference_func
 * <li>GDExtensionClassCreateInstance2 create_instance_func
 * <li>GDExtensionClassFreeInstance free_instance_func
 * <li>GDExtensionClassRecreateInstance recreate_instance_func
 * <li>GDExtensionClassGetVirtual2 get_virtual_func
 * <li>GDExtensionClassGetVirtualCallData2 get_virtual_call_data_func
 * <li>void* class_userdata
 * </ol>
 */
public final class InstanceCallbacks {

	private static final Logger logger = LogManager.getLogger(InstanceCallbacks.class);

	private InstanceCallbacks() {
	}

	// ------------------------------------------------------------------------
	// Struct layout — GDExtensionClassCreationInfo4
	// Offsets auto-generated by StructLayoutComputer from
	// gdextension_interface.json
	// ------------------------------------------------------------------------

	// ------------------------------------------------------------------------
	// Registration tracking — keeps native allocations alive
	// ------------------------------------------------------------------------

	/**
	 * Registered classes: Godot class name → Java Class. Updated by
	 * {@link #registerClass(String, Class)}.
	 */
	private static final Map<String, Class<? extends Godot>> REGISTERED_CLASSES = new ConcurrentHashMap<>();

	/**
	 * Maps class_userdata pointer address → Godot class name. Used by
	 * create_instance_func to look up the class from the opaque userdata pointer.
	 */
	private static final Map<Long, String> USERDATA_TO_CLASS_NAME = new ConcurrentHashMap<>();

	/**
	 * Extension class name → parent class name in Godot's hierarchy. Used by
	 * create_instance_func to construct the native parent object.
	 */
	private static final Map<String, String> PARENT_CLASS_NAMES = new ConcurrentHashMap<>();

	/**
	 * Live creation info structs: className → struct MemorySegment. The struct
	 * memory stays alive because the Arena never frees until JVM shutdown.
	 */
	private static final Map<String, MemorySegment> LIVE_CREATION_INFO = new ConcurrentHashMap<>();

	/**
	 * Property fields per class: className → (propertyName → Field). Used by
	 * set/get callbacks to access @Export fields via reflection.
	 */
	private static final Map<String, Map<String, java.lang.reflect.Field>> PROPERTY_FIELDS = new ConcurrentHashMap<>();

	// APT-generated typed dispatch: className → TypedDispatch class
	private static final Map<String, Class<?>> APT_DISPATCH_CACHE = new ConcurrentHashMap<>();

	// ------------------------------------------------------------------------
	// Upcall stubs — kept alive by the Arena (freed at JVM shutdown)
	// ------------------------------------------------------------------------

	private static final Map<String, MemorySegment> CREATE_INSTANCE_STUBS = new ConcurrentHashMap<>();
	private static final Map<String, MemorySegment> FREE_INSTANCE_STUBS = new ConcurrentHashMap<>();

	// ------------------------------------------------------------------------
	// Internal helpers
	// ------------------------------------------------------------------------

	/**
	 * Look up a registered Java class by Godot class name.
	 */
	private static Class<? extends Godot> getRegisteredClass(String className) {
		return REGISTERED_CLASSES.get(className);
	}

	// ------------------------------------------------------------------------
	// Upcall stub implementations
	//
	// These methods are called by Godot via the native function pointers
	// we register. They must match the GDExtension FFI calling convention.
	//
	// GDExtensionClassCreateInstance2:
	// void* create_instance_func(void* p_class_userdata, GDExtensionBool
	// p_notify_postinitialize)
	// → returns GDExtensionObjectPtr
	//
	// GDExtensionClassFreeInstance:
	// void free_instance_func(void* p_class_userdata, GDExtensionClassInstancePtr
	// p_instance)
	// ------------------------------------------------------------------------

	/**
	 * create_instance_func implementation.
	 *
	 * @param classUserdataPtr
	 *            Address of the class name StringName (stored as class_userdata)
	 * @param notifyPostinit
	 *            GDExtensionBool — if true, call postinitialize()
	 * @return GDExtensionObjectPtr
	 */
	static long createInstanceFunc(long classUserdataPtr, int notifyPostinit) {
		if (classUserdataPtr == 0) {
			logger.error("createInstanceFunc: classUserdata is NULL");
			return 0;
		}

		String className = USERDATA_TO_CLASS_NAME.get(classUserdataPtr);
		if (className == null) {
			logger.error("createInstanceFunc: no class mapping for userdata=0x{}", Long.toHexString(classUserdataPtr));
			return 0;
		}
		Class<? extends Godot> clazz = getRegisteredClass(className);

		if (clazz == null) {
			logger.error("No registered class for '{}'", className);
			return 0;
		}

		try {
			// Look up parent class name for native construction
			String parentName = PARENT_CLASS_NAMES.getOrDefault(className, "RefCounted");

			// Construct the native Godot object using the parent class
			GodotStringName parentSn = GodotStringName.fromJavaString(parentName);
			MemorySegment nativeObj = Bridge.callPtr(ApiIndex.CLASSDB_CONSTRUCT_OBJECT2, parentSn.segment());
			long nativePtr = nativeObj.address();

			if (nativePtr == 0) {
				logger.error("classdb_construct_object2('{}') returned NULL", parentName);
				return 0;
			}

			// Create Java instance and bind to native object
			Godot instance = clazz.getDeclaredConstructor().newInstance();
			// Set nativeObject via reflection (protected field in different package)
			java.lang.reflect.Field nativeObjField = Godot.class.getDeclaredField("nativeObject");
			nativeObjField.setAccessible(true);
			nativeObjField.set(instance, nativePtr);
			JavaObjectMap.put(nativePtr, instance);

			// Register the extension instance with Godot so virtual dispatch works.
			// object_set_instance(GDExtensionObjectPtr, StringName*,
			// GDExtensionClassInstancePtr)
			// The instance pointer is the native object address — dispatch uses it to look
			// up the Java object.
			GodotStringName classNameSn = GodotStringName.fromJavaString(className);
			Bridge.callVoid(ApiIndex.OBJECT_SET_INSTANCE, nativeObj, classNameSn.segment(), nativeObj);

			return nativePtr;
		} catch (Exception e) {
			throw new RuntimeException("godot-java: Failed to instantiate " + className, e);
		}
	}

	// ------------------------------------------------------------------------
	// Panama upcall adapters
	//
	// Panama FFI requires upcall method handles to accept MemorySegment arguments
	// (representing native pointers). These adapters unpack the segments to
	// primitives, call the actual implementation, then pack the result back.
	// ------------------------------------------------------------------------

	/**
	 * Panama adapter for create_instance_func. FD: ADDRESS
	 * create_instance_adapter(ADDRESS classUserdataPtr, JAVA_INT notifyPostinit)
	 * Unpacks MemorySegments → calls createInstanceFunc → returns MemorySegment.
	 */
	private static MemorySegment createInstanceAdapter(MemorySegment classUserdataPtrSeg, int notifyPostinit) {
		long result = createInstanceFunc(classUserdataPtrSeg.address(), notifyPostinit);
		return MemorySegment.ofAddress(result);
	}

	/**
	 * free_instance_func implementation.
	 *
	 * @param classUserdataPtr
	 *            Address of the class name StringName (stored as class_userdata)
	 * @param instancePtr
	 *            GDExtensionClassInstancePtr to destroy
	 */
	static void freeInstanceFunc(long classUserdataPtr, long instancePtr) {
		if (instancePtr != 0) {
			Godot obj = JavaObjectMap.get(instancePtr);
			if (obj != null) {
				obj.invalidate();
			}
			JavaObjectMap.remove(instancePtr);
			org.godot.internal.NativeMemoryTracker.onFree(instancePtr);
		}
	}

	/**
	 * Panama adapter for free_instance_func. FD: void free_instance_adapter(ADDRESS
	 * classUserdataPtr, ADDRESS instancePtr) Unpacks MemorySegments → calls
	 * freeInstanceFunc.
	 */
	private static void freeInstanceAdapter(MemorySegment classUserdataPtrSeg, MemorySegment instancePtrSeg) {
		freeInstanceFunc(classUserdataPtrSeg.address(), instancePtrSeg.address());
	}

	// ------------------------------------------------------------------------
	// set_func / get_func — @Export property access callbacks
	// ------------------------------------------------------------------------

	/**
	 * set_func implementation: called by Godot to set a property value.
	 *
	 * @param instancePtr
	 *            GDExtensionClassInstancePtr (the native object pointer)
	 * @param namePtr
	 *            Pointer to StringName containing the property name
	 * @param valuePtr
	 *            Pointer to Variant containing the new value
	 * @return 1 if property was handled, 0 otherwise
	 */
	static int setPropertyFunc(long instancePtr, long namePtr, long valuePtr) {
		Object obj = JavaObjectMap.get(instancePtr);
		if (obj == null)
			return 0;

		String className = obj.getClass().getAnnotation(GodotClass.class).name();

		// Convert StringName to Java String
		String propName = stringNamePtrToString(namePtr);

		// Read Variant value
		MemorySegment valueSeg = MemorySegment.ofAddress(valuePtr).reinterpret(16);
		Variant variant = new Variant(valueSeg);
		Object javaValue = VariantUtils.toObject(variant);

		// Try APT-generated typed dispatch first (VarHandle, zero-reflection)
		Class<?> aptDispatch = loadAptDispatch(className);
		if (aptDispatch != null) {
			try {
				Method setMethod = aptDispatch.getMethod("setProperty", String.class, Godot.class, Object.class);
				boolean handled = (boolean) setMethod.invoke(null, propName, obj, javaValue);
				if (handled)
					return 1;
			} catch (Exception e) {
				logger.trace("APT setProperty failed for {}.{}: {}", className, propName, e.getMessage());
			}
		}

		// Fallback: reflection-based field access
		Map<String, java.lang.reflect.Field> fields = PROPERTY_FIELDS.get(className);
		if (fields == null)
			return 0;

		java.lang.reflect.Field field = fields.get(propName);
		if (field == null)
			return 0;

		try {
			Class<?> type = field.getType();
			Object converted = convertToType(javaValue, type);
			field.setAccessible(true);
			field.set(obj, converted);
			return 1; // handled
		} catch (Exception e) {
			logger.error("setPropertyFunc failed for {}.{}: {}", className, propName, e.getMessage());
			return 0;
		}
	}

	/**
	 * get_func implementation: called by Godot to get a property value.
	 */
	static int getPropertyFunc(long instancePtr, long namePtr, long retPtr) {
		Object obj = JavaObjectMap.get(instancePtr);
		if (obj == null)
			return 0;

		String className = obj.getClass().getAnnotation(GodotClass.class).name();
		String propName = stringNamePtrToString(namePtr);
		Object value = null;

		// Try APT-generated typed dispatch first (VarHandle, zero-reflection)
		Class<?> aptDispatch = loadAptDispatch(className);
		if (aptDispatch != null) {
			try {
				Method getMethod = aptDispatch.getMethod("getProperty", String.class, Godot.class);
				value = getMethod.invoke(null, propName, obj);
			} catch (Exception e) {
				logger.trace("APT getProperty failed for {}.{}: {}", className, propName, e.getMessage());
			}
		}

		// Fallback: reflection-based field access
		if (value == null) {
			Map<String, java.lang.reflect.Field> fields = PROPERTY_FIELDS.get(className);
			if (fields == null)
				return 0;

			java.lang.reflect.Field field = fields.get(propName);
			if (field == null)
				return 0;

			try {
				field.setAccessible(true);
				value = field.get(obj);
			} catch (Exception e) {
				logger.error("getPropertyFunc failed for {}.{}: {}", className, propName, e.getMessage());
				return 0;
			}
		}

		if (value == null)
			return 0;

		try {
			Variant variant = VariantUtils.fromObject(value);
			MemorySegment retSeg = MemorySegment.ofAddress(retPtr).reinterpret(Variant.SIZE);
			MemorySegment srcSeg = variant.getSegment().reinterpret(Variant.SIZE);
			MemorySegment.copy(srcSeg, 0, retSeg, 0, Variant.SIZE);
			return 1;
		} catch (Exception e) {
			logger.error("getPropertyFunc variant conversion failed for {}.{}: {}", className, propName,
					e.getMessage());
			return 0;
		}
	}

	/** Load APT-generated TypedDispatch_<ClassName> for typed property access. */
	private static Class<?> loadAptDispatch(String godotClassName) {
		return APT_DISPATCH_CACHE.computeIfAbsent(godotClassName, name -> {
			try {
				return Class.forName("org.godot.internal.TypedDispatch_" + name);
			} catch (ClassNotFoundException e) {
				return null;
			}
		});
	}

	private static String stringNamePtrToString(long namePtr) {
		try {
			// Read the StringName opaque handle from the pointer (8 bytes)
			MemorySegment nameData = MemorySegment.ofAddress(namePtr).reinterpret(8);
			long handle = nameData.get(JAVA_LONG, 0);

			// Create a temporary StringName Variant from the pointer data
			MemorySegment variantBuf = Bridge.allocate(16);
			variantBuf.set(JAVA_INT, 0, org.godot.internal.api.VariantType.STRING_NAME.id());
			variantBuf.set(JAVA_LONG, 8, handle);

			// Use variant_stringify to convert to String
			MemorySegment retBuf = Bridge.allocate(8);
			Bridge.callVoid(org.godot.internal.api.ApiIndex.VARIANT_STRINGIFY, variantBuf, retBuf);
			return new org.godot.core.GodotString(retBuf).toJavaString();
		} catch (Exception e) {
			logger.error("stringNamePtrToString failed: {}", e.getMessage());
			return "";
		}
	}

	/** Convert a Variant result to the expected Java field type. */
	private static Object convertToType(Object value, Class<?> targetType) {
		if (value == null)
			return null;
		if (targetType == float.class || targetType == Float.class) {
			if (value instanceof Number n)
				return n.floatValue();
		}
		if (targetType == int.class || targetType == Integer.class) {
			if (value instanceof Number n)
				return n.intValue();
		}
		if (targetType == double.class || targetType == Double.class) {
			if (value instanceof Number n)
				return n.doubleValue();
		}
		if (targetType == long.class || targetType == Long.class) {
			if (value instanceof Number n)
				return n.longValue();
		}
		if (targetType == boolean.class || targetType == Boolean.class) {
			if (value instanceof Boolean b)
				return b;
		}
		return value;
	}

	/** Panama adapter for set_func: bool set(ADDRESS, ADDRESS, ADDRESS) */
	private static int setPropertyAdapter(MemorySegment instanceSeg, MemorySegment nameSeg, MemorySegment valueSeg) {
		return setPropertyFunc(instanceSeg.address(), nameSeg.address(), valueSeg.address());
	}

	/** Panama adapter for get_func: bool get(ADDRESS, ADDRESS, ADDRESS) */
	private static int getPropertyAdapter(MemorySegment instanceSeg, MemorySegment nameSeg, MemorySegment retSeg) {
		return getPropertyFunc(instanceSeg.address(), nameSeg.address(), retSeg.address());
	}

	// ------------------------------------------------------------------------
	// notification_func — Godot notification forwarding
	// ------------------------------------------------------------------------

	/**
	 * notification_func implementation: called by Godot to deliver notifications
	 * (e.g., NOTIFICATION_READY, NOTIFICATION_ENTER_TREE, NOTIFICATION_DRAW).
	 *
	 * @param instancePtr
	 *            GDExtensionClassInstancePtr
	 * @param what
	 *            Notification constant (e.g., 13 = NOTIFICATION_READY)
	 * @param reversed
	 *            Whether notification propagation is reversed
	 */
	static void notificationFunc(long instancePtr, int what, int reversed) {
		Godot obj = JavaObjectMap.get(instancePtr);
		if (obj != null) {
			obj.onNotification(what);
		}
	}

	/** Panama adapter for notification_func: void(ADDRESS, JAVA_INT, JAVA_INT) */
	private static void notificationAdapter(MemorySegment instanceSeg, int what, int reversed) {
		notificationFunc(instanceSeg.address(), what, reversed);
	}

	// ------------------------------------------------------------------------
	// to_string_func — Java toString() bridge
	// ------------------------------------------------------------------------

	/**
	 * to_string_func implementation: called by Godot to get a string representation
	 * of the extension object.
	 *
	 * @param instancePtr
	 *            GDExtensionClassInstancePtr
	 * @param retPtr
	 *            Pointer to write the resulting GodotString (8 bytes opaque handle)
	 * @param classUserdataPtr
	 *            class_userdata pointer (unused)
	 */
	static void toStringFunc(long instancePtr, long retPtr, long classUserdataPtr) {
		Object obj = JavaObjectMap.get(instancePtr);
		String result;
		if (obj != null) {
			result = obj.toString();
		} else {
			result = "<freed object>";
		}

		if (retPtr != 0) {
			GodotString gs = GodotString.fromJavaString(result);
			MemorySegment retSeg = MemorySegment.ofAddress(retPtr).reinterpret(8);
			MemorySegment.copy(gs.segment(), 0, retSeg, 0, 8);
		}
	}

	/** Panama adapter for to_string_func: void(ADDRESS, ADDRESS, ADDRESS) */
	private static void toStringAdapter(MemorySegment instanceSeg, MemorySegment retSeg, MemorySegment userdataSeg) {
		toStringFunc(instanceSeg.address(), retSeg.address(), userdataSeg.address());
	}

	// ------------------------------------------------------------------------
	// reference_func / unreference_func — RefCounted lifecycle
	// ------------------------------------------------------------------------

	/**
	 * reference_func implementation: called by Godot when a RefCounted object's
	 * reference count is incremented. Ensures the Java wrapper stays alive.
	 *
	 * @param instancePtr
	 *            GDExtensionClassInstancePtr
	 */
	static void referenceFunc(long instancePtr) {
		// Java wrapper stays in JavaObjectMap as long as Godot holds a reference.
		// No action needed — the Java GC won't collect it while the map holds it.
		logger.trace("reference_func: instance=0x{}", Long.toHexString(instancePtr));
	}

	/**
	 * unreference_func implementation: called by Godot when a RefCounted object's
	 * reference count is decremented. When refcount reaches 0, invalidates the Java
	 * wrapper.
	 *
	 * @param instancePtr
	 *            GDExtensionClassInstancePtr
	 */
	static void unreferenceFunc(long instancePtr) {
		// When Godot decrements to 0, the object will be freed via free_instance_func.
		// We just log here; actual cleanup happens in freeInstanceFunc.
		logger.trace("unreference_func: instance=0x{}", Long.toHexString(instancePtr));
	}

	/** Panama adapter for reference_func: void(ADDRESS) */
	private static void referenceAdapter(MemorySegment instanceSeg) {
		referenceFunc(instanceSeg.address());
	}

	/** Panama adapter for unreference_func: void(ADDRESS) */
	private static void unreferenceAdapter(MemorySegment instanceSeg) {
		unreferenceFunc(instanceSeg.address());
	}

	// ------------------------------------------------------------------------
	// get_property_list_func / free_property_list_func
	// ------------------------------------------------------------------------

	private static final Map<String, MemorySegment> PROPERTY_LIST_ALLOCS = new ConcurrentHashMap<>();

	/**
	 * get_property_list_func: returns the list of @Export properties as a
	 * GDExtensionPropertyInfo array.
	 */
	static long getPropertyListFunc(long instancePtr, long countPtr) {
		Object obj = JavaObjectMap.get(instancePtr);
		if (obj == null) {
			writeInt(countPtr, 0);
			return 0;
		}

		String className = obj.getClass().getAnnotation(GodotClass.class).name();
		Map<String, java.lang.reflect.Field> fields = PROPERTY_FIELDS.get(className);
		if (fields == null || fields.isEmpty()) {
			writeInt(countPtr, 0);
			return 0;
		}

		int count = fields.size();
		writeInt(countPtr, count);

		// Allocate array of PropertyInfo structs
		long allocSize = StructOffsets.PROPERTY_INFO_SIZE * count;
		MemorySegment listBuf = Bridge.allocate(allocSize);
		PROPERTY_LIST_ALLOCS.put(className + "@" + instancePtr, listBuf);

		int i = 0;
		for (Map.Entry<String, java.lang.reflect.Field> entry : fields.entrySet()) {
			String propName = entry.getKey();
			java.lang.reflect.Field field = entry.getValue();
			Export export = field.getAnnotation(Export.class);
			VariantType type = PropertyRegistration.javaTypeToVariantType(field.getType());

			long offset = i * StructOffsets.PROPERTY_INFO_SIZE;
			listBuf.set(JAVA_INT, offset + StructOffsets.PROPERTY_INFO_OFF_TYPE, type.id());

			GodotStringName nameSn = GodotStringName.fromJavaString(propName);
			listBuf.set(ADDRESS, offset + StructOffsets.PROPERTY_INFO_OFF_NAME,
					MemorySegment.ofAddress(nameSn.segment().address()));
			// class_name (StringName*) — MUST be valid pointer, Godot dereferences
			// unconditionally
			GodotStringName emptySn = GodotStringName.fromJavaString("");
			listBuf.set(ADDRESS, offset + StructOffsets.PROPERTY_INFO_OFF_CLASS_NAME,
					MemorySegment.ofAddress(emptySn.segment().address()));

			PropertyHint hint = export.hint();
			listBuf.set(JAVA_INT, offset + StructOffsets.PROPERTY_INFO_OFF_HINT, hint.id());

			String hintStr = export.hintString();
			GodotString hintString = hintStr.isEmpty()
					? GodotString.fromJavaString("")
					: GodotString.fromJavaString(hintStr);
			listBuf.set(ADDRESS, offset + StructOffsets.PROPERTY_INFO_OFF_HINT_STRING,
					MemorySegment.ofAddress(hintString.segment().address()));

			listBuf.set(JAVA_INT, offset + StructOffsets.PROPERTY_INFO_OFF_USAGE, 1 | 4 | 8);

			i++;
		}

		return listBuf.address();
	}

	/** Panama adapter for get_property_list_func: ADDRESS(ADDRESS, ADDRESS) */
	private static MemorySegment getPropertyListAdapter(MemorySegment instanceSeg, MemorySegment countSeg) {
		long result = getPropertyListFunc(instanceSeg.address(), countSeg.address());
		return MemorySegment.ofAddress(result);
	}

	/**
	 * free_property_list_func: called by Godot to free the property list.
	 */
	static void freePropertyListFunc(long instancePtr, long listPtr, int count) {
		String className = null;
		Object obj = JavaObjectMap.get(instancePtr);
		if (obj != null) {
			className = obj.getClass().getAnnotation(GodotClass.class).name();
		}
		if (className != null) {
			PROPERTY_LIST_ALLOCS.remove(className + "@" + instancePtr);
		}
	}

	/**
	 * Panama adapter for free_property_list_func: void(ADDRESS, ADDRESS, JAVA_INT)
	 */
	private static void freePropertyListAdapter(MemorySegment instanceSeg, MemorySegment listSeg, int count) {
		freePropertyListFunc(instanceSeg.address(), listSeg.address(), count);
	}

	// ------------------------------------------------------------------------
	// property_can_revert_func / property_get_revert_func
	// ------------------------------------------------------------------------

	/**
	 * property_can_revert_func: returns true if a default value is known for the
	 * property.
	 */
	static int propertyCanRevertFunc(long instancePtr, long namePtr) {
		Object obj = JavaObjectMap.get(instancePtr);
		if (obj == null)
			return 0;

		String className = obj.getClass().getAnnotation(GodotClass.class).name();
		Map<String, java.lang.reflect.Field> fields = PROPERTY_FIELDS.get(className);
		if (fields == null)
			return 0;

		String propName = stringNamePtrToString(namePtr);
		if (!fields.containsKey(propName))
			return 0;

		// If the field has a non-default value, we can revert to the class default
		return 1;
	}

	private static int propertyCanRevertAdapter(MemorySegment instanceSeg, MemorySegment nameSeg) {
		return propertyCanRevertFunc(instanceSeg.address(), nameSeg.address());
	}

	/**
	 * property_get_revert_func: returns the default value for a property.
	 */
	static int propertyGetRevertFunc(long instancePtr, long namePtr, long retPtr) {
		Object obj = JavaObjectMap.get(instancePtr);
		if (obj == null)
			return 0;

		String className = obj.getClass().getAnnotation(GodotClass.class).name();
		Map<String, java.lang.reflect.Field> fields = PROPERTY_FIELDS.get(className);
		if (fields == null)
			return 0;

		String propName = stringNamePtrToString(namePtr);
		java.lang.reflect.Field field = fields.get(propName);
		if (field == null)
			return 0;

		try {
			// Get the default value from a fresh instance
			Class<?> clazz = obj.getClass();
			Object fresh = clazz.getDeclaredConstructor().newInstance();
			field.setAccessible(true);
			Object defaultVal = field.get(fresh);

			Variant variant = VariantUtils.fromObject(defaultVal);
			MemorySegment retSeg = MemorySegment.ofAddress(retPtr).reinterpret(Variant.SIZE);
			MemorySegment.copy(variant.getSegment().reinterpret(Variant.SIZE), 0, retSeg, 0, Variant.SIZE);
			return 1;
		} catch (ReflectiveOperationException e) {
			return 0;
		}
	}

	private static int propertyGetRevertAdapter(MemorySegment instanceSeg, MemorySegment nameSeg,
			MemorySegment retSeg) {
		return propertyGetRevertFunc(instanceSeg.address(), nameSeg.address(), retSeg.address());
	}

	// ------------------------------------------------------------------------
	// validate_property_func
	// ------------------------------------------------------------------------

	/**
	 * validate_property_func: basic validation pass-through. Always returns true
	 * (property is valid). Can be extended later for range/enumeration validation.
	 */
	static int validatePropertyFunc(long instancePtr, long propertyInfoPtr) {
		return 1;
	}

	private static int validatePropertyAdapter(MemorySegment instanceSeg, MemorySegment propertyInfoSeg) {
		return validatePropertyFunc(instanceSeg.address(), propertyInfoSeg.address());
	}

	private static void writeInt(long ptr, int value) {
		if (ptr != 0) {
			MemorySegment.ofAddress(ptr).reinterpret(4).set(JAVA_INT, 0, value);
		}
	}

	// ------------------------------------------------------------------------
	// Native string helpers — removed; class name lookup via USERDATA_TO_CLASS_NAME
	// ------------------------------------------------------------------------

	// ------------------------------------------------------------------------
	// Public API
	// ------------------------------------------------------------------------

	/**
	 * Register a Java class so it can be instantiated by Godot via the
	 * create_instance_func callback.
	 *
	 * <p>
	 * This must be called before {@link #createCreationInfo} for each class.
	 *
	 * @param godotClassName
	 *            The Godot class name (from @GodotClass annotation)
	 * @param javaClass
	 *            The Java class to instantiate
	 */
	public static void registerClass(String godotClassName, Class<? extends Godot> javaClass) {
		REGISTERED_CLASSES.put(godotClassName, javaClass);
		// Store parent class name from @GodotClass annotation
		GodotClass annotation = javaClass.getAnnotation(GodotClass.class);
		if (annotation != null) {
			PARENT_CLASS_NAMES.put(godotClassName, annotation.parent());
		}
		// Collect @Export fields for set/get callbacks
		Map<String, java.lang.reflect.Field> propFields = new java.util.HashMap<>();
		for (java.lang.reflect.Field f : javaClass.getDeclaredFields()) {
			if (f.isAnnotationPresent(org.godot.annotation.Export.class)) {
				org.godot.annotation.Export export = f.getAnnotation(org.godot.annotation.Export.class);
				String propName = export.propertyName().isEmpty() ? f.getName() : export.propertyName();
				f.setAccessible(true);
				propFields.put(propName, f);
			}
		}
		if (!propFields.isEmpty()) {
			PROPERTY_FIELDS.put(godotClassName, propFields);
		}
	}

	/**
	 * Get the registered Java class for a Godot class name.
	 */
	public static Class<?> getJavaClass(String godotClassName) {
		return REGISTERED_CLASSES.get(godotClassName);
	}

	/**
	 * Get the parent Godot class name for a registered class.
	 */
	public static String getParentClassName(String godotClassName) {
		return PARENT_CLASS_NAMES.get(godotClassName);
	}

	/**
	 * Create and return a native GDExtensionClassCreationInfo4 struct for the given
	 * class.
	 *
	 * <p>
	 * This allocates memory in the shared Bridge Arena and populates all 22 fields.
	 * The mandatory fields set are:
	 * <ul>
	 * <li>create_instance_func → our upcall stub
	 * <li>free_instance_func → our upcall stub
	 * <li>class_userdata → address of the class name StringName
	 * </ul>
	 *
	 * @param godotClassName
	 *            The Godot class name (used as class_userdata key)
	 * @return MemorySegment pointing to the allocated struct (176 bytes)
	 */
	public static MemorySegment createCreationInfo(String godotClassName) {
		// Create the StringName for class_userdata
		GodotStringName classNameSn = GodotStringName.fromJavaString(godotClassName);
		long classNamePtr = classNameSn.segment().address();

		// Build create_instance_func upcall stub
		// FD: ADDRESS createInstanceAdapter(ADDRESS classUserdataPtr, JAVA_INT
		// notifyPostinit)
		FunctionDescriptor createFd = FunctionDescriptor.of(ADDRESS, ADDRESS, JAVA_INT);
		MethodHandle createHandle;
		try {
			createHandle = MethodHandles.lookup().unreflect(
					InstanceCallbacks.class.getDeclaredMethod("createInstanceAdapter", MemorySegment.class, int.class));
		} catch (ReflectiveOperationException e) {
			throw new RuntimeException("Failed to create createInstance upcall handle", e);
		}
		MemorySegment createStub = Bridge.linker().upcallStub(createHandle, createFd, Bridge.ARENA);
		CREATE_INSTANCE_STUBS.put(godotClassName, createStub);

		// Build free_instance_func upcall stub
		// FD: void freeInstanceAdapter(ADDRESS classUserdataPtr, ADDRESS instancePtr)
		FunctionDescriptor freeFd = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS);
		MethodHandle freeHandle;
		try {
			freeHandle = MethodHandles.lookup().unreflect(InstanceCallbacks.class
					.getDeclaredMethod("freeInstanceAdapter", MemorySegment.class, MemorySegment.class));
		} catch (ReflectiveOperationException e) {
			throw new RuntimeException("Failed to create freeInstance upcall handle", e);
		}
		MemorySegment freeStub = Bridge.linker().upcallStub(freeHandle, freeFd, Bridge.ARENA);
		FREE_INSTANCE_STUBS.put(godotClassName, freeStub);

		// Allocate the creation info struct (160 bytes)
		MemorySegment info = Bridge.allocate(StructOffsets.CREATION_INFO4_SIZE);

		// Zero-initialize the entire struct
		for (long i = 0; i < StructOffsets.CREATION_INFO4_SIZE; i += 8) {
			info.set(ADDRESS, i, MemorySegment.ofAddress(0));
		}

		// Set mandatory fields
		// is_exposed = true (byte offset 2, GDExtensionBool = uint8_t)
		info.set(ValueLayout.JAVA_BYTE, StructOffsets.CREATION_INFO4_OFF_IS_EXPOSED, (byte) 1);
		// create_instance_func
		info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_CREATE_INSTANCE_FUNC,
				MemorySegment.ofAddress(createStub.address()));
		// free_instance_func
		info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_FREE_INSTANCE_FUNC,
				MemorySegment.ofAddress(freeStub.address()));
		// class_userdata = address of StringName struct
		info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_CLASS_USERDATA, MemorySegment.ofAddress(classNamePtr));

		// Map userdata pointer → class name for create_instance lookup
		USERDATA_TO_CLASS_NAME.put(classNamePtr, godotClassName);

		// set_func / get_func — property access callbacks for @Export fields
		if (PROPERTY_FIELDS.containsKey(godotClassName)) {
			FunctionDescriptor propFd = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS);
			try {
				MethodHandle setHandle = MethodHandles.lookup().unreflect(InstanceCallbacks.class.getDeclaredMethod(
						"setPropertyAdapter", MemorySegment.class, MemorySegment.class, MemorySegment.class));
				MemorySegment setStub = Bridge.linker().upcallStub(setHandle, propFd, Bridge.ARENA);
				info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_SET_FUNC,
						MemorySegment.ofAddress(setStub.address()));

				MethodHandle getHandle = MethodHandles.lookup().unreflect(InstanceCallbacks.class.getDeclaredMethod(
						"getPropertyAdapter", MemorySegment.class, MemorySegment.class, MemorySegment.class));
				MemorySegment getStub = Bridge.linker().upcallStub(getHandle, propFd, Bridge.ARENA);
				info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_GET_FUNC,
						MemorySegment.ofAddress(getStub.address()));
			} catch (ReflectiveOperationException e) {
				throw new RuntimeException("Failed to create property access upcall stubs", e);
			}
		}

		// Field 20: get_virtual_func = per-class upcall stub for virtual method
		// dispatch
		MemorySegment getVirtualStub = VirtualDispatch.getGetVirtualFuncStubForClass(godotClassName);
		info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_GET_VIRTUAL_FUNC,
				MemorySegment.ofAddress(getVirtualStub.address()));

		// validate_property_func — basic validation pass-through (always accepts)
		FunctionDescriptor validatePropFd = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS);
		try {
			MethodHandle validatePropHandle = MethodHandles.lookup().unreflect(InstanceCallbacks.class
					.getDeclaredMethod("validatePropertyAdapter", MemorySegment.class, MemorySegment.class));
			MemorySegment validatePropStub = Bridge.linker().upcallStub(validatePropHandle, validatePropFd,
					Bridge.ARENA);
			info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_VALIDATE_PROPERTY_FUNC,
					MemorySegment.ofAddress(validatePropStub.address()));
		} catch (ReflectiveOperationException e) {
			throw new RuntimeException("Failed to create validate_property_func upcall stub", e);
		}

		// notification_func — forward Godot notifications to Java
		FunctionDescriptor notifyFd = FunctionDescriptor.ofVoid(ADDRESS, JAVA_INT, JAVA_INT);
		try {
			MethodHandle notifyHandle = MethodHandles.lookup().unreflect(InstanceCallbacks.class
					.getDeclaredMethod("notificationAdapter", MemorySegment.class, int.class, int.class));
			MemorySegment notifyStub = Bridge.linker().upcallStub(notifyHandle, notifyFd, Bridge.ARENA);
			info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_NOTIFICATION_FUNC,
					MemorySegment.ofAddress(notifyStub.address()));
		} catch (ReflectiveOperationException e) {
			throw new RuntimeException("Failed to create notification_func upcall stub", e);
		}

		// to_string_func — bridge Java toString() to Godot
		FunctionDescriptor toStringFd = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, ADDRESS);
		try {
			MethodHandle toStringHandle = MethodHandles.lookup().unreflect(InstanceCallbacks.class.getDeclaredMethod(
					"toStringAdapter", MemorySegment.class, MemorySegment.class, MemorySegment.class));
			MemorySegment toStringStub = Bridge.linker().upcallStub(toStringHandle, toStringFd, Bridge.ARENA);
			info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_TO_STRING_FUNC,
					MemorySegment.ofAddress(toStringStub.address()));
		} catch (ReflectiveOperationException e) {
			throw new RuntimeException("Failed to create to_string_func upcall stub", e);
		}

		// reference_func / unreference_func — only for RefCounted-derived classes
		if (isRefCountedParent(godotClassName)) {
			FunctionDescriptor refFd = FunctionDescriptor.ofVoid(ADDRESS);
			try {
				MethodHandle refHandle = MethodHandles.lookup()
						.unreflect(InstanceCallbacks.class.getDeclaredMethod("referenceAdapter", MemorySegment.class));
				MemorySegment refStub = Bridge.linker().upcallStub(refHandle, refFd, Bridge.ARENA);
				info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_REFERENCE_FUNC,
						MemorySegment.ofAddress(refStub.address()));

				MethodHandle unrefHandle = MethodHandles.lookup().unreflect(
						InstanceCallbacks.class.getDeclaredMethod("unreferenceAdapter", MemorySegment.class));
				MemorySegment unrefStub = Bridge.linker().upcallStub(unrefHandle, refFd, Bridge.ARENA);
				info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_UNREFERENCE_FUNC,
						MemorySegment.ofAddress(unrefStub.address()));
			} catch (ReflectiveOperationException e) {
				throw new RuntimeException("Failed to create reference/unreference upcall stubs", e);
			}
		}

		if (PROPERTY_FIELDS.containsKey(godotClassName)) {
			// get_property_list_func / free_property_list_func
			FunctionDescriptor getPropListFd = FunctionDescriptor.of(ADDRESS, ADDRESS, ADDRESS);
			FunctionDescriptor freePropListFd = FunctionDescriptor.ofVoid(ADDRESS, ADDRESS, JAVA_INT);
			try {
				MethodHandle getPropListHandle = MethodHandles.lookup().unreflect(InstanceCallbacks.class
						.getDeclaredMethod("getPropertyListAdapter", MemorySegment.class, MemorySegment.class));
				MemorySegment getPropListStub = Bridge.linker().upcallStub(getPropListHandle, getPropListFd,
						Bridge.ARENA);
				info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_GET_PROPERTY_LIST_FUNC,
						MemorySegment.ofAddress(getPropListStub.address()));

				MethodHandle freePropListHandle = MethodHandles.lookup()
						.unreflect(InstanceCallbacks.class.getDeclaredMethod("freePropertyListAdapter",
								MemorySegment.class, MemorySegment.class, int.class));
				MemorySegment freePropListStub = Bridge.linker().upcallStub(freePropListHandle, freePropListFd,
						Bridge.ARENA);
				info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_FREE_PROPERTY_LIST_FUNC,
						MemorySegment.ofAddress(freePropListStub.address()));
			} catch (ReflectiveOperationException e) {
				throw new RuntimeException("Failed to create property list upcall stubs", e);
			}

			// property_can_revert_func / property_get_revert_func
			FunctionDescriptor canRevertFd = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS);
			FunctionDescriptor getRevertFd = FunctionDescriptor.of(JAVA_INT, ADDRESS, ADDRESS, ADDRESS);
			try {
				MethodHandle canRevertHandle = MethodHandles.lookup().unreflect(InstanceCallbacks.class
						.getDeclaredMethod("propertyCanRevertAdapter", MemorySegment.class, MemorySegment.class));
				MemorySegment canRevertStub = Bridge.linker().upcallStub(canRevertHandle, canRevertFd, Bridge.ARENA);
				info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_PROPERTY_CAN_REVERT_FUNC,
						MemorySegment.ofAddress(canRevertStub.address()));

				MethodHandle getRevertHandle = MethodHandles.lookup()
						.unreflect(InstanceCallbacks.class.getDeclaredMethod("propertyGetRevertAdapter",
								MemorySegment.class, MemorySegment.class, MemorySegment.class));
				MemorySegment getRevertStub = Bridge.linker().upcallStub(getRevertHandle, getRevertFd, Bridge.ARENA);
				info.set(ADDRESS, StructOffsets.CREATION_INFO4_OFF_PROPERTY_GET_REVERT_FUNC,
						MemorySegment.ofAddress(getRevertStub.address()));
			} catch (ReflectiveOperationException e) {
				throw new RuntimeException("Failed to create property revert upcall stubs", e);
			}
		}

		LIVE_CREATION_INFO.put(godotClassName, info);
		return info;
	}

	/**
	 * Check if the parent class of the given registered class inherits from
	 * RefCounted. Uses the generated Java class hierarchy to determine this
	 * dynamically - covers all Godot engine types without a hardcoded list.
	 */
	private static boolean isRefCountedParent(String godotClassName) {
		String parent = PARENT_CLASS_NAMES.get(godotClassName);
		if (parent == null) {
			return false;
		}
		if ("RefCounted".equals(parent)) {
			return true;
		}
		try {
			Class<?> parentClass = Class.forName("org.godot.node." + parent);
			return org.godot.core.RefCounted.class.isAssignableFrom(parentClass);
		} catch (ClassNotFoundException e) {
			return false;
		}
	}
}
