package org.godot.bridge;

import org.godot.core.GodotString;
import org.godot.core.GodotStringName;
import org.godot.internal.api.ApiIndex;
import org.godot.internal.api.StructOffsets;
import org.godot.internal.api.VariantType;
import org.godot.internal.dispatch.Dispatch;
import org.godot.internal.dispatch.PropertyMeta;
import java.lang.foreign.MemorySegment;
import static java.lang.foreign.ValueLayout.*;

/**
 * Handles registration of @Export annotated fields as Godot properties.
 *
 * <p>
 * Uses compile-time metadata from {@link Dispatch} instead of runtime
 * reflection. All property metadata is generated by APT into DispatchIndex.
 *
 * <p>
 * GDExtensionPropertyInfo layout (48 bytes on 64-bit):
 * <ul>
 * <li>offset 0: type (int32_t) — VariantType enum</li>
 * <li>offset 8: name (StringName*)</li>
 * <li>offset 16: class_name (StringName*)</li>
 * <li>offset 24: hint (uint32_t)</li>
 * <li>offset 32: hint_string (StringPtr*)</li>
 * <li>offset 40: usage (uint32_t)</li>
 * </ul>
 *
 * <p>
 * classdb_register_extension_class_property(library, className, propertyInfo*)
 */
public final class PropertyRegistration {

	private PropertyRegistration() {
	}

	// PROPERTY_USAGE_DEFAULT = 1, PROPERTY_USAGE_EDITOR = 4, PROPERTY_USAGE_STORAGE
	// = 8
	private static final int PROPERTY_USAGE_DEFAULT = 1 | 4 | 8;

	// Shared empty strings — Godot dereferences ALL string pointers unconditionally
	private static final GodotStringName EMPTY_SN = GodotStringName.fromJavaString("");
	private static final GodotString EMPTY_STR = GodotString.fromJavaString("");

	/**
	 * Register all @Export annotated fields of a class.
	 *
	 * <p>
	 * Note: Property data (type, hint, hintString, usage) is now provided to Godot
	 * via {@code get_property_list_func} in InstanceCallbacks, which exposes them
	 * to the Inspector. The ClassDB registration path is intentionally disabled
	 * because using both paths simultaneously causes duplicate properties and
	 * crashes the editor during DocTools::generate().
	 */
	public static int registerProperties(String className) {
		return Dispatch.getExports(className).length;
	}

	private static void registerProperty(String godotClassName, PropertyMeta meta) {
		// Build PropertyInfo struct
		MemorySegment propertyInfo = buildPropertyInfo(meta);

		// Register: classdb_register_extension_class_property(library, className,
		// propertyInfo*, setter_name, getter_name)
		GodotStringName classSn = GodotStringName.fromJavaString(godotClassName);

		Bridge.callVoid(ApiIndex.CLASSDB_REGISTER_EXTENSION_CLASS_PROPERTY,
				MemorySegment.ofAddress(Bridge.libraryPtr()), classSn.segment(), propertyInfo, EMPTY_SN.segment(),
				EMPTY_SN.segment());
	}

	private static MemorySegment buildPropertyInfo(PropertyMeta meta) {
		VariantType type = stringTypeToVariantType(meta.typeName());

		MemorySegment info = Bridge.allocate(StructOffsets.PROPERTY_INFO_SIZE);

		// type (uint32_t)
		info.set(JAVA_INT, StructOffsets.PROPERTY_INFO_OFF_TYPE, type.id());
		// name (StringName*) — Godot dereferences unconditionally
		GodotStringName nameSn = GodotStringName.fromJavaString(meta.godotName());
		info.set(ADDRESS, StructOffsets.PROPERTY_INFO_OFF_NAME, MemorySegment.ofAddress(nameSn.segment().address()));
		// class_name (StringName*) — MUST be valid pointer
		info.set(ADDRESS, StructOffsets.PROPERTY_INFO_OFF_CLASS_NAME,
				MemorySegment.ofAddress(EMPTY_SN.segment().address()));
		// hint (uint32_t)
		info.set(JAVA_INT, StructOffsets.PROPERTY_INFO_OFF_HINT, meta.hintId());
		// hint_string (String*) — MUST be valid pointer
		String hintStr = meta.hintString();
		GodotString hintString = hintStr.isEmpty() ? EMPTY_STR : GodotString.fromJavaString(hintStr);
		info.set(ADDRESS, StructOffsets.PROPERTY_INFO_OFF_HINT_STRING,
				MemorySegment.ofAddress(hintString.segment().address()));
		// usage (uint32_t)
		info.set(JAVA_INT, StructOffsets.PROPERTY_INFO_OFF_USAGE, PROPERTY_USAGE_DEFAULT);

		return info;
	}

	/**
	 * Map Java type name strings (from APT-generated metadata) to VariantType. Used
	 * by property registration which operates on compile-time metadata.
	 */
	static VariantType stringTypeToVariantType(String typeName) {
		if (typeName == null)
			return VariantType.OBJECT;
		return switch (typeName) {
			case "boolean", "java.lang.Boolean" -> VariantType.BOOL;
			case "byte", "java.lang.Byte" -> VariantType.INT;
			case "short", "java.lang.Short" -> VariantType.INT;
			case "int", "java.lang.Integer" -> VariantType.INT;
			case "long", "java.lang.Long" -> VariantType.INT;
			case "float", "java.lang.Float" -> VariantType.FLOAT;
			case "double", "java.lang.Double" -> VariantType.FLOAT;
			case "java.lang.String" -> VariantType.STRING;
			case "org.godot.math.Vector2" -> VariantType.VECTOR2;
			case "org.godot.math.Vector3" -> VariantType.VECTOR3;
			case "org.godot.math.Vector2i" -> VariantType.VECTOR2I;
			case "org.godot.math.Vector3i" -> VariantType.VECTOR3I;
			default -> VariantType.OBJECT;
		};
	}

	/**
	 * Map Java Class types to VariantType. Retained for use by
	 * InstanceCallbacks.getPropertyListFunc which still uses Field-based access.
	 */
	static VariantType javaTypeToVariantType(Class<?> type) {
		if (type == boolean.class || type == Boolean.class)
			return VariantType.BOOL;
		if (type == byte.class || type == Byte.class)
			return VariantType.INT;
		if (type == short.class || type == Short.class)
			return VariantType.INT;
		if (type == int.class || type == Integer.class)
			return VariantType.INT;
		if (type == long.class || type == Long.class)
			return VariantType.INT;
		if (type == float.class || type == Float.class)
			return VariantType.FLOAT;
		if (type == double.class || type == Double.class)
			return VariantType.FLOAT;
		if (type == String.class)
			return VariantType.STRING;
		if (type == org.godot.math.Vector2.class)
			return VariantType.VECTOR2;
		if (type == org.godot.math.Vector3.class)
			return VariantType.VECTOR3;
		if (type == org.godot.math.Vector2i.class)
			return VariantType.VECTOR2I;
		if (type == org.godot.math.Vector3i.class)
			return VariantType.VECTOR3I;
		// Default to OBJECT for Godot types
		return VariantType.OBJECT;
	}
}
