package org.godot.bridge;

import org.godot.core.GodotString;
import org.godot.core.GodotStringName;
import org.godot.internal.api.ApiIndex;
import org.godot.internal.api.StructOffsets;
import org.godot.internal.dispatch.Dispatch;
import org.godot.internal.dispatch.SignalMeta;
import java.lang.foreign.MemorySegment;
import static java.lang.foreign.ValueLayout.*;

/**
 * Handles registration of @Signal annotated methods as Godot signals.
 *
 * <p>
 * Uses compile-time metadata from {@link Dispatch} instead of runtime
 * reflection. All signal metadata is generated by APT into DispatchIndex.
 *
 * <p>
 * classdb_register_extension_class_signal(library, className, signalName,
 * argumentInfo*, argCount)
 *
 * <p>
 * Method parameters become signal argument names. If the method has no
 * parameters, the signal has no arguments.
 */
public final class SignalRegistration {

	private SignalRegistration() {
	}

	// Shared empty strings — Godot dereferences ALL string pointers unconditionally
	private static final GodotStringName EMPTY_SN = GodotStringName.fromJavaString("");
	private static final GodotString EMPTY_STR = GodotString.fromJavaString("");

	/**
	 * Register all @Signal annotated methods of a class as Godot signals.
	 */
	public static int registerSignals(String className) {
		SignalMeta[] signals = Dispatch.getSignals(className);
		if (signals.length == 0)
			return 0;

		int count = 0;
		for (SignalMeta meta : signals) {
			registerSignal(className, meta);
			count++;
		}
		return count;
	}

	private static void registerSignal(String godotClassName, SignalMeta meta) {
		GodotStringName signalSn = GodotStringName.fromJavaString(meta.name());
		GodotStringName classSn = GodotStringName.fromJavaString(godotClassName);

		// Build argument info array from signal parameter types/names
		String[] paramTypes = meta.paramTypes();
		String[] paramNames = meta.paramNames();
		int argCount = (paramTypes != null) ? paramTypes.length : 0;
		MemorySegment argumentInfo = buildArgumentInfo(paramTypes, paramNames);

		// Register: classdb_register_extension_class_signal(library, className,
		// signalName, argumentInfo*, argCount)
		Bridge.callVoid4S1L(ApiIndex.CLASSDB_REGISTER_EXTENSION_CLASS_SIGNAL,
				MemorySegment.ofAddress(Bridge.libraryPtr()), classSn.segment(), signalSn.segment(), argumentInfo,
				(long) argCount);
	}

	/**
	 * Build an array of GDExtensionPropertyInfo structs for signal arguments. Each
	 * PropertyInfo is 48 bytes. All string fields MUST be valid pointers.
	 */
	private static MemorySegment buildArgumentInfo(String[] paramTypes, String[] paramNames) {
		if (paramTypes == null || paramTypes.length == 0) {
			return MemorySegment.NULL;
		}

		int argCount = paramTypes.length;
		long totalSize = (long) argCount * StructOffsets.PROPERTY_INFO_SIZE;
		MemorySegment array = Bridge.allocate(totalSize);

		for (int i = 0; i < argCount; i++) {
			long offset = (long) i * StructOffsets.PROPERTY_INFO_SIZE;
			// type (uint32_t)
			int typeId = stringTypeToVariantTypeId(paramTypes[i]);
			array.set(JAVA_INT, offset + StructOffsets.PROPERTY_INFO_OFF_TYPE, typeId);
			// name (StringName*) — MUST be valid pointer
			String paramName = (paramNames != null && i < paramNames.length) ? paramNames[i] : "arg" + i;
			GodotStringName argNameSn = GodotStringName.fromJavaString(paramName);
			array.set(ADDRESS, offset + StructOffsets.PROPERTY_INFO_OFF_NAME,
					MemorySegment.ofAddress(argNameSn.segment().address()));
			// class_name (StringName*) — MUST be valid pointer
			array.set(ADDRESS, offset + StructOffsets.PROPERTY_INFO_OFF_CLASS_NAME,
					MemorySegment.ofAddress(EMPTY_SN.segment().address()));
			// hint (uint32_t) = 0
			// hint_string (String*) — MUST be valid pointer
			array.set(ADDRESS, offset + StructOffsets.PROPERTY_INFO_OFF_HINT_STRING,
					MemorySegment.ofAddress(EMPTY_STR.segment().address()));
			// usage (uint32_t) = 0
		}

		return array;
	}

	private static int stringTypeToVariantTypeId(String typeName) {
		if (typeName == null)
			return 24; // OBJECT
		return switch (typeName) {
			case "boolean", "java.lang.Boolean" -> 1; // BOOL
			case "int", "java.lang.Integer" -> 2; // INT
			case "long", "java.lang.Long" -> 2; // INT
			case "float", "java.lang.Float" -> 3; // FLOAT
			case "double", "java.lang.Double" -> 3; // FLOAT
			case "java.lang.String" -> 4; // STRING
			default -> 24; // OBJECT
		};
	}
}
