package com.godot.codegen;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.TreeMap;

/**
 * Generates {@code ObjectMethodHashes.java} containing method hashes for
 * Godot's Object class. This is used by {@code Godot.call()} as a fallback when
 * resolving Object-level methods like {@code emit_signal}.
 *
 * <p>
 * The hashes are read from {@code extension_api.json} so they stay in sync with
 * the targeted Godot version automatically.
 */
public class ObjectHashGenerator {

	public static void genObjectHashes(Map<String, ClassInfo> classMap, String outputDir, String packageName)
			throws IOException {
		ClassInfo objectClass = classMap.get("Object");
		if (objectClass == null) {
			System.err.println("Warning: Object class not found in API, skipping hash generation");
			return;
		}

		// Collect non-virtual, non-underscore method hashes sorted by name
		Map<String, Long> hashes = new TreeMap<>();
		for (MethodInfo method : objectClass.methods()) {
			if (!method.name().startsWith("_") && method.hash() != 0) {
				hashes.put(method.name(), method.hash());
			}
		}

		if (hashes.isEmpty()) {
			System.err.println("Warning: No Object method hashes found");
			return;
		}

		// Build Java source
		StringBuilder sb = new StringBuilder();
		sb.append("package ").append(packageName).append(";\n\n");
		sb.append("/**\n");
		sb.append(" * Auto-generated method hashes for Godot's Object class.\n");
		sb.append(" * Used by {@code org.godot.Godot.call()} as fallback for Object-level methods.\n");
		sb.append(" * DO NOT EDIT - regenerated by code generator.\n");
		sb.append(" */\n");
		sb.append("public final class ObjectMethodHashes {\n\n");
		sb.append("\tprivate ObjectMethodHashes() {}\n\n");
		sb.append("\t/** Method hashes for Godot's Object class. */\n");
		sb.append("\tpublic static final java.util.Map<String, Long> HASHES = java.util.Map.ofEntries(\n");

		int i = 0;
		for (Map.Entry<String, Long> entry : hashes.entrySet()) {
			sb.append("\t\tjava.util.Map.entry(\"");
			sb.append(entry.getKey());
			sb.append("\", ");
			sb.append(entry.getValue());
			sb.append("L)");
			if (i < hashes.size() - 1) {
				sb.append(",");
			}
			sb.append("\n");
			i++;
		}
		sb.append("\t);\n}\n");

		// Write to file
		String packagePath = packageName.replace('.', '/');
		Path dirPath = Path.of(outputDir, packagePath);
		Files.createDirectories(dirPath);
		Path filePath = dirPath.resolve("ObjectMethodHashes.java");
		try (BufferedWriter writer = Files.newBufferedWriter(filePath, StandardCharsets.UTF_8)) {
			writer.write(sb.toString());
		}

		System.out.println("Generated: ObjectMethodHashes.java (" + hashes.size() + " methods)");
	}
}
