package org.godot.node;

/**
 * Auto-generated method hashes for Godot's Object class. Used by
 * {@code org.godot.Godot.call()} as fallback for Object-level methods. DO NOT
 * EDIT - regenerated by code generator.
 */
public final class ObjectMethodHashes {

	private ObjectMethodHashes() {
	}

	/** Method hashes for Godot's Object class. */
	public static final java.util.Map<String, Long> HASHES = java.util.Map.ofEntries(
			java.util.Map.entry("add_user_signal", 85656714L), java.util.Map.entry("call", 3400424181L),
			java.util.Map.entry("call_deferred", 3400424181L), java.util.Map.entry("callv", 1260104456L),
			java.util.Map.entry("can_translate_messages", 36873697L), java.util.Map.entry("cancel_free", 3218959716L),
			java.util.Map.entry("connect", 1518946055L), java.util.Map.entry("disconnect", 1874754934L),
			java.util.Map.entry("emit_signal", 4047867050L), java.util.Map.entry("get", 2760726917L),
			java.util.Map.entry("get_class", 201670096L), java.util.Map.entry("get_incoming_connections", 3995934104L),
			java.util.Map.entry("get_indexed", 4006125091L), java.util.Map.entry("get_instance_id", 3905245786L),
			java.util.Map.entry("get_meta", 3990617847L), java.util.Map.entry("get_meta_list", 3995934104L),
			java.util.Map.entry("get_method_argument_count", 2458036349L),
			java.util.Map.entry("get_method_list", 3995934104L), java.util.Map.entry("get_property_list", 3995934104L),
			java.util.Map.entry("get_script", 1214101251L),
			java.util.Map.entry("get_signal_connection_list", 3147814860L),
			java.util.Map.entry("get_signal_list", 3995934104L),
			java.util.Map.entry("get_translation_domain", 2002593661L),
			java.util.Map.entry("has_connections", 2619796661L), java.util.Map.entry("has_meta", 2619796661L),
			java.util.Map.entry("has_method", 2619796661L), java.util.Map.entry("has_signal", 2619796661L),
			java.util.Map.entry("has_user_signal", 2619796661L), java.util.Map.entry("is_blocking_signals", 36873697L),
			java.util.Map.entry("is_class", 3927539163L), java.util.Map.entry("is_connected", 768136979L),
			java.util.Map.entry("is_queued_for_deletion", 36873697L), java.util.Map.entry("notification", 4023243586L),
			java.util.Map.entry("notify_property_list_changed", 3218959716L),
			java.util.Map.entry("property_can_revert", 2619796661L),
			java.util.Map.entry("property_get_revert", 2760726917L), java.util.Map.entry("remove_meta", 3304788590L),
			java.util.Map.entry("remove_user_signal", 3304788590L), java.util.Map.entry("set", 3776071444L),
			java.util.Map.entry("set_block_signals", 2586408642L), java.util.Map.entry("set_deferred", 3776071444L),
			java.util.Map.entry("set_indexed", 3500910842L),
			java.util.Map.entry("set_message_translation", 2586408642L), java.util.Map.entry("set_meta", 3776071444L),
			java.util.Map.entry("set_script", 1114965689L), java.util.Map.entry("set_translation_domain", 3304788590L),
			java.util.Map.entry("to_string", 2841200299L), java.util.Map.entry("tr", 1195764410L),
			java.util.Map.entry("tr_n", 162698058L));
}
